[package]
name = "rose-offline-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.4"
arrayvec = "0.7"
async-trait = "0.1"
bevy = { version = "0.8.0", features = ["dds", "tga"] }
bevy_egui = "0.15.0"
bevy-inspector-egui = "0.12.1"
bevy_polyline = "0.3.0"
bevy_rapier3d = "0.16.0"
bitflags = "1.2"
bytemuck = { version = "1.7.0", features = ["derive"] }
chrono = "0.4"
clap = "3.2"
cpal = "0.13"
crossbeam-channel = "0.5"
directories = "4.0"
dolly = "0.3.1"
egui_extras = "0.18"
enum-map = { version = "2.0", features = ["serde"] }
hound = "3.4"
image = { version = "0.24", default-features = false, features = ["dds"] }
lazy_static = "1.4.0"
lewton = "0.10"
log = "0.4.14"
md5 = "0.7.0"
num-derive = "0.3"
num-traits = "0.2"
oddio = "0.5"
rand = "0.8"
serde = "1.0"
thiserror = "1.0"
tokio = { version = "1.17", features = ["rt", "net", "sync", "macros", "io-util"] }
toml = "0.5.9"
quick-xml = { version = "0.23", features = ["serialize"] }
rose-data = { git = "https://github.com/exjam/rose-offline", rev = "a7b6b49c722f92d98d673f27c2b535c9b8974fd3" }
rose-data-irose = { git = "https://github.com/exjam/rose-offline", rev = "a7b6b49c722f92d98d673f27c2b535c9b8974fd3" }
rose-file-readers = { git = "https://github.com/exjam/rose-offline", rev = "a7b6b49c722f92d98d673f27c2b535c9b8974fd3" }
rose-game-common = { git = "https://github.com/exjam/rose-offline", rev = "a7b6b49c722f92d98d673f27c2b535c9b8974fd3" }
rose-game-irose = { git = "https://github.com/exjam/rose-offline", rev = "a7b6b49c722f92d98d673f27c2b535c9b8974fd3" }
rose-network-common = { git = "https://github.com/exjam/rose-offline", rev = "a7b6b49c722f92d98d673f27c2b535c9b8974fd3" }
rose-network-irose = { git = "https://github.com/exjam/rose-offline", rev = "a7b6b49c722f92d98d673f27c2b535c9b8974fd3" }

[patch.crates-io]
bevy = { git = "https://github.com/exjam/bevy", rev = "88e688d68c9b31d14baa7582c67cb92877847c32" }
bevy_polyline = { git = "https://github.com/exjam/bevy_polyline", rev = "3c7bae575481f5a561442a8327f0f465c092917b" }
bevy_egui = { git = "https://github.com/exjam/bevy_egui", rev = "9e9c47b51f2cc18812070580cc9d0fa8feeebb13" }
bevy-inspector-egui = { git = "https://github.com/exjam/bevy-inspector-egui", rev = "a1a4379b0fe787e4830ce7b919fa75cfc2b6390b" }
bevy_rapier3d = { git = "https://github.com/exjam/bevy_rapier", rev = "f0809f556fb2e97eba3fd1a07d50ab522e2f57df" }
oddio = { git = "https://github.com/exjam/oddio", rev = "4f4eb4076c3a4068225a7c442a25e40422261c93" }

[profile.dev.package."*"]
opt-level = 3
